### ISSUE TITLE
Show bid history for an auction(let)

### ISSUE THREAD

**Issue by rainbeam** [makerdao/weekly-mkr-auction#52]
Similar to 'last trades' in the market.

**Comment by gbalabasquer** [comment]
Hi @rainbeam, to be sure about the requirement, this is for the case when we have selected one specific auction, not?. So it will show the auction/auctionlet, the last bid (as it does now) and then a history of the previous bids?  In positive case, any more info about how it needs to be done? Will it be a table under the last bid, or we should use tabs to change between last bidder and history?

**Comment by rainbeam** [comment]
I was thinking for a specific auction, so you can see the full history of bids (and layer, splits).

However you could also have a global list, filtered by trade pair.

As for implementation I'm not sure what would be best - don't want to clutter the UI, so maybe it would be hidden initially. Best talk with geronimo and others in chat.

**Comment by gbalabasquer** [comment]
Thanks, I'll check it with geronimo in the chat. Anyway for now I need to wait until the new token-auction contract is deployed with the changes in the Bid Event Log.
