### ISSUE TITLE
use AuctionManager instead of SplittingAuctionManager

### ISSUE THREAD

**Issue by rainbeam** [makerdao/weekly-mkr-auction#53]
As far as I can tell, `SplittingAuctionManager` is the deployed contract that the frontend is interacting with.

This allows users to split the auction - I'm not sure how this will play out in the UI.

If you want to limit users to non-splitting auctions then link to a deployed `AuctionManager` instead.

**Comment by jorisbontje** [comment]
Yeah, it is communicating with the `SplittingAuctionManager`. However we have all intention to add support for this to the current UI.

**Comment by rainbeam** [comment]
Ok. My only concern is trolling in the interim.
